#!/bin/bash
# usage: ./Projectfile [command]

#
# develop
#

images () {
  docker compose build --parallel
}

up () {
  docker compose up --detach "$@"
}

shell () {
  up && docker compose exec shell /bin/bash -l
}

down () {
  docker compose stop
}

clean () {
  docker compose rm -s -f -v
}

#
# helpers
#

test () {
  up && docker compose exec shell ./test/suite
}

lint () {
  up && docker compose exec shell bundle exec rubocop
}

fix () {
  up && docker compose exec shell bundle exec rubocop -a
}

#
# utility
#

list () {
  compgen -A function
}

if list | grep -qFx -- "${1:-}"
then "$@"; exit $?
else
  printf "unknown command: %s\n" "${1:-}" >&2
  exit 1
fi
