#!/bin/bash
. test/integration/helper

test_cat_reads_from_stdin_by_default () {
printf "%s\n" abc | $CAT | assert_output "\
abc
"
}

test_cat_concatenates_files () {
printf "%s\n" c | $CAT <(printf "%s\n" a b) - | assert_output "\
a
b
c
"
}

#
# -h
#

test_h_prints_help () {
$CAT -h | grep -q "usage: $CAT"
}

#
# -u
#

test_u_unbuffers_output () {
start_time="$(date +%s)"
n_tries=0
while [ "$n_tries" -lt 20 ]
do
   printf "%s\n" "$n_tries"
   sleep 0.1
   n_tries="$((n_tries + 1))"
done | $CAT -u | grep -q '.'
end_time="$(date +%s)"

[ $((end_time - start_time)) -lt 2 ]
assert_status $? 0 "output was not unbuffered"
}

. ts
