#!/bin/bash

test_rbcat_reads_from_stdin_by_default () {
printf "%s\n" abc | rbcat | assert_output "\
abc
"
}

test_rbcat_concatenates_files () {
printf "%s\n" c | rbcat <(printf "%s\n" a b) - | assert_output "\
a
b
c
"
}

#
# -h
#

test_h_prints_help () {
rbcat -h | grep -q "usage: rbcat"
}

. ts
